version: '3.8'

services:
  # Backend service
  backend:
    build: ./backend
    container_name: expense_logger_api
    volumes:
      - ./backend:/app
      - uploaded_files:/app/uploads
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres_db
      - DB_NAME=expense_logger
      - DB_USER=postgres
      - DB_PASSWORD=secret
      # Add environment variable for max upload size
      - MAX_UPLOAD_SIZE=10485760  # 10MB in bytes
    depends_on:
      - postgres_db
    restart: unless-stopped
    # Override command to include larger request size limits
    command: >
      uvicorn main:app 
      --host 0.0.0.0 
      --port 8000 
      --reload 
      --timeout-keep-alive 300

  # Frontend service
  frontend:
    build: ./frontend
    container_name: expense_logger_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped

  # Database service
  postgres_db:
    image: postgres:15
    container_name: expense_logger_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=expense_logger
    restart: unless-stopped

volumes:
  postgres_data:
  uploaded_files: